Live-Coding-Test/Algorithm-study

week1/1_1299/송지민_1299.java, week1/2_2942/송지민_2942.java, week1/3_897/송지민_897.java, week1/4_637/송지민_637.java, week1/5_338/송지민_338.java, week1/6_1757/송지민_1757.sql, week1/7_228/송지민_228.java, week1/개인문제/송지민_1399.java, week1/개인문제/송지민_181.sql, week1/개인문제/송지민_238.java, week1/개인문제/송지민_322.java, week1/개인문제/송지민_442.java, week1/개인문제/송지민_744.java, week1/개인문제/송지민_98.java
=> [송지민] 1주차 과제 제출

week1/1_1299/이지은_1299.js, week1/2_2942/이지은_2942.js, week1/3_897/이지은_897.js, week1/4_637/이지은_637.js, week1/5_338/이지은_338.js, week1/6_1757/이지은_1757.sql, week1/7_228/이지은_228.js
=> [이지은] 1주차 과제 제출

week1/1_1299/박희경_1299.java, week1/2_2942/박희경_2942.java, week1/3_897/박희경_897.java, week1/4_637/박희경_637.java
=> [박희경] 1주차 과제 제출

week2/1_121/김선재_121.js, week2/4_463/김선재_463.js, week2/5_841/김선재_841.js, week2/6_189/김선재_189.js, week2/7_1068/김선재_1068.sql
2 : 530
3 : 112
두 문제 풀이 못했습니다..!
=> [김선재] 2주차 과제 제출

week2/1_121/정우희_121.js, week2/2_530/정우희_530.js, week2/3_112/정우희_112.js, week2/4_463/정우희_463.js, week2/5_841/정우희_841.js, week2/6_189/정우희_189.js, week2/7_1068/정우희_1068.sql
=> week2 문제풀이 제출

week5/1_2996/박희경_2996.java, week5/2_404/박희경_404.java, week5/5_1137/박희경_1137.java, week6/1_2914/박희경_2914.java, week6/3_1025/박희경_1025.java, week6/5_1143/박희경_1143.java
=> [박희경] 5, 6주차 과제 제출

week12/1_64061/박희경_64061.py, week12/2_135808/박희경_135808.py, week12/3_individual/박희경_개인문제1.py, week12/4_individual/박희경_개인문제2.py, week12/5_individual/박희경_개인문제3.py
이코테 문제 풀이 중 난이도가 낮아 6시 이후 유형별 기출 더 풀어볼 예정
=> [박희경] 12주차 과제 제출

week14/1_1829/정우희_150370.js, week14/2_81302/정우희_81302.js, week14/3_individual/정우희_개인문제1.js, week14/4_individual/정우희_개인문제2.js, week14/5_individual/정우희_개인문제3.js
=> [정우희] 14주차 과제 제출

week15/1_10026/박희경_10026.py, week15/2_11725/박희경_11725.py, week15/3_individual/박희경_개인문제1.py, week15/4_individual/박희경_개인문제2.py, week15/5_individual/박희경_개인문제3.py
개인문제 1 : [연구소](https://www.acmicpc.net/problem/14502)
개인문제 2: [괄호 변환](https://school.programmers.co.kr/learn/courses/30/lessons/60058)
개인문제 3: [연산자 끼워 넣기](https://www.acmicpc.net/problem/14888)
=> [박희경] 15주차 과제 제출

week16/1_17681/박희경_17681.py, week16/2_49189/박희경_49189.py, week16/3_individual/박희경_개인문제1.java, week16/4_individual/박희경_개인문제2.java, week16/5_individual/박희경_개인문제3.py
개인문제1: [k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
개인문제2: [이웃한 칸](https://school.programmers.co.kr/learn/courses/30/lessons/250125)
개인문제3: [바이러스](https://www.acmicpc.net/problem/2606)
=> [박희경] 16주차 과제 제출

week16/5_individual/박희경_개인문제3.py, week17/1_60057/박희경_60057.py, week17/2_60059/박희경_60059.py, week17/3_individual/박희경_개인문제1.py, week17/4_individual/박희경_개인문제2.py, week17/5_individual/박희경_개인문제3.py
개인문제1: [덧칠하기](https://school.programmers.co.kr/learn/courses/30/lessons/161989)
개인문제2: [미로탐색](https://www.acmicpc.net/problem/2178)
개인문제3: [스타트와 링크](https://www.acmicpc.net/problem/14889)
=> [박희경] 17주차 과제 제출

week18/1_42895/박희경_42895.py, week18/2_42898/박희경_42898.py, week18/3_individual/박희경_개인문제1.py, week18/4_individual/박희경_개인문제2.py, week18/5_individual/박희경_개인문제3.py
개인문제1: [계단 오르기](https://www.acmicpc.net/problem/2579)
개인문제2: [스티커](https://www.acmicpc.net/problem/9465)
개인문제3: [동전1](https://www.acmicpc.net/problem/2293)
=> [박희경] 18주차 과제 제출

week19/1_12913/박희경_12913.py, week19/2_2579/박희경_2579.py, week19/3_individual/박희경_개인문제1.py, week19/4_individual/박희경_개인문제2.py, week19/5_individual/박희경_개인문제3.py
개인문제1: [1로 만들기](https://www.acmicpc.net/problem/1463)
개인문제2: [1, 2, 3 더하기](https://www.acmicpc.net/problem/9095)
개인문제3: [1로 만들기2](https://www.acmicpc.net/problem/12852)
=> [박희경] 19주차 과제 제출

week21/1_12919/박희경_12919.py, week21/2_1189/박희경_1189.py, week21/3_individual/박희경_개인문제1.py, week21/4_individual/박희경_개인문제2.py
개인문제 1: [차이를 최대로](https://www.acmicpc.net/problem/10819)
개인문제 2: [숨바꼭질](https://www.acmicpc.net/problem/1697)
=> [박희경] 21주차 과제 제출

week25/1_1743/박희경_1743.py, week25/2_7576/박희경_7576.py, week25/3_individual/박희경_개인문제1.py, week25/4_individual/박희경_개인문제2.py, week25/5_individual/박희경_개인문제3.py
개인문제1: [단지번호붙이기](https://www.acmicpc.net/problem/2667)
개인문제2: [촌수계산](https://www.acmicpc.net/problem/2644)
개인문제3: [토마토](https://www.acmicpc.net/problem/7569) (공통문제 2번 3차원 버전)
=> [박희경] 25주차 과제 제출

test4/문제1(140107)/박희경.py, test4/문제2(68644)/박희경.py, test4/문제3(136798)/박희경.py
=> [박희경] 4차 라이브 코테 제출

test8/문제1/박희경.py, test8/문제2/박희경.py, test8/문제3/박희경.py
=> [박희경] 8차 라이브 코테 제출

test8/문제1/김진용.py, test8/문제2/김진용.py, test8/문제3/김진용.py
=> [김진용] 8차 라이브 코테 제출

test11/문제1/박희경.py, test11/문제2/박희경.py, test11/문제3/박희경.py
1번: O (누적합 부분 인터넷 참고)
2번: O
3번: X (시도X)
=> [박희경] 11차 라이브 코테 제출

test12/문제1/박희경.py, test12/문제2/박희경.py, test12/문제3/박희경.py
=> [박희경] 12차 라이브 코테 제출

test13/문제1/김진용.py, test13/문제2/김진용.py, test13/문제3/김진용.py
1번: 못 풀음 -> O
2번: O
3번: X (시간초과 -> O
=> [김진용] 13차 라이브 코테 제출

test14/문제1/박희경.py, test14/문제2/박희경.py, test14/문제3/박희경.py
=> [박희경] 14차 라이브 코테 제출

test15/문제1/박희경.py, test15/문제2/박희경.py, test15/문제3/박희경.py
=> [박희경] 15차 라이브 코테 제출

test16/문제1/박희경.py, test16/문제2/박희경.py, test16/문제3/박희경.py
1번: O (여기서 너무 시간 뺏김)
2번: X (시도x)
3번: X (시간부족)
=> [박희경] 16차 라이브 코테 제출

test16/문제1/김진용.py, test16/문제2/김진용.py, test16/문제3/김진용.py
=> [김진용] 16차 라이브 코테 제출

test17/문제1/김진용.py, test17/문제2/김진용.py, test17/문제3/김진용.py
=> [김진용] 17차 라이브 코테 제출

test18/문제1/박희경.py, test18/문제2/박희경.py
=> [박희경] 18차 라이브 코테 제출

test18/문제1/임동민.js, test18/문제2/임동민.js
=> [임동민] 18차 라이브 코테 제출

test19/문제1/김진용.py, test19/문제2/김진용.py, test19/문제3/김진용.py
=> [김진용] 19차 라이브 코테 제출

test18/문제3/임동민.js, test19/문제1/임동민.js, test19/문제2/임동민.js, test19/문제3/임동민.js
=> [임동민] 19차 라이브코테 제출

test19/문제1/박희경.py, test19/문제2/박희경.py, test19/문제3/박희경.py
1번 : X (실패)
2번: X (시간부족)
3번: X (시도X)
=> [박희경] 19차 라이브 코테 제출

test19/문제3/김진용.py, test20/문제1/김진용.py, test20/문제2/김진용.py
1 - O
2 - O(4달 전 나한테 참고)
3 - x
=> [김진용] 20차 라이브 코테 제출

test20/문제1/최지혜.py
=> [최지혜] 20차 라이브코테 제출

test20/문제1/박희경.py, test20/문제2/박희경.py, test20/문제3/박희경.py
=> [박희경] 20차 라이브 코테 제출

test20/문제1/임동민.js, test20/문제2/임동민.js, test20/문제3/임동민.js
1-결석 (다시 푼 문제)
2-결석 (다시 푼 문제)
3-결석 (다시 푼 문제)
=> [임동민] 20차 라이브 코테 제출

test21/문제1/박희경.py, test21/문제2/박희경.py
1번: O (참고)
2번: X (시간부족)
3번: X (시도X)
=> [박희경] 21차 라이브 코테 제출

test21/문제1/임동민.js, test21/문제2/임동민.js, test21/문제3/임동민.js
=> [임동민] 21차 라이브 코테 제출

test22/문제1/김진용.py, test22/문제2/김진용.py, test22/문제3/김진용.py
1 - O(참고.. 이해... 완료)
2 - O(참고.. 이해.. 완료..)
3 - O(순수 내 힘으로 풀음 뿌듯)
=> [김진용] 22차 라이브 코테 제출

test22/문제1/박희경.py, test22/문제2/박희경.py, test22/문제3/박희경.py
=> [박희경] 22차 라이브 코테 제출

test22/문제1/임동민.js, test22/문제2/임동민.js, test22/문제3/임동민.js
1-O
2-X ( 메모리 초과 )
3-X ( 시도 X )
=> [임동민] 22차 라이브 코테 제출

test23/문제1/김진용.py, test23/문제2/김진용.py, test23/문제3/김진용.py
=> [김진용] 23차 라이브 코테 제출

test23/문제1/박희경.py, test23/문제2/박희경.py, test23/문제3/박희경.py
=> [박희경] 23차 라이브 코테 제출

test23/문제1/임동민.js, test23/문제2/임동민.js, test23/문제3/임동민.js
1-O ( 참고 )
2-X ( 시도 중 )
3-X ( 시도 X )
=> [임동민] 23차 라이브 코테 제출

test24/문제1/박희경.py, test24/문제2/박희경.py, test24/문제3/박희경.py
=> [박희경] 24차 라이브 코테 제출

test24/문제1/김진용.py, test24/문제2/김진용.py, test24/문제3/김진용.py
=> [김진용] 24차 라이브 코테 제출

test25/문제1/박희경.py, test25/문제2/박희경.py, test25/문제3/박희경.py
=> [박희경] 25차 라이브 코테 제출

test25/문제1/임동민.js, test25/문제2/임동민.js, test25/문제3/임동민.js
=> [임동민] 25차 라이브 코테 제출

test25/문제1/김진용.py, test25/문제2/김진용.py, test25/문제3/김진용.py
=> [김진용] 25차 라이브 코테 제출

test26/문제1/김진용.py, test26/문제2/김진용.py, test26/문제3/김진용.py
=> [김진용] 26차 라이브 코테 제출

test26/문제1/박희경.py, test26/문제2/박희경.py, test26/문제3/박희경.py
1번: O (참고)
2번: O (참고)
3번: X (시도X)
=> [박희경] 26차 라이브 코테 제출

test27/문제1/최지혜.py, test27/문제2/최지혜.py
=> [최지혜] 27차 라이브코테 제출

test27/문제1/김진용.py, test27/문제2/김진용.py, test27/문제3/김진용.py
1 - (참고 - 문제 이해 안 됨)
2 - O
3 - O
=> [김진용] 27차 라이브 코테 제출

test27/문제1/박희경.py, test27/문제2/박희경.py, test27/문제3/박희경.py
=> [박희경] 27차 라이브 코테 제출

test26/문제1/임동민.js, test26/문제2/임동민.js, test26/문제3/임동민.js, test27/문제1/임동민.js, test27/문제2/임동민.js, test27/문제3/임동민.js
1-X ( 권한관련 런타임에러 )
2-O 
3-X ( 푸는중 )
=> [임동민] 27차 라이브코테 제출

test27/문제1/김진용.py, test28/문제1/김진용.py, test28/문제2/김진용.py, test28/문제3/김진용.py
1 - O
2 - O
3 - O(풀긴 풀었는데 이상함 채점이 안 됨)
=> [김진용] 28차 라이브 코테 제출

test28/문제1/임동민.js
=> [임동민] 28차 라이브 코테 제출

test29/문제1/최지혜.py, test29/문제2/최지혜.py, test29/문제3/최지혜.py
=> [최지혜] 29차 라이브코테 제출

test29/문제1/황장현.js, test29/문제3/황장현.js
=> [황장현] 29차 라이브코테 제출

test29/문제1/김진용.py, test29/문제2/김진용.py, test29/문제3/김진용.py
=> [김진용] 29차 라이브 코테 제출

test29/문제1/박희경.py, test29/문제2/박희경.py, test29/문제3/박희경.py
=> [박희경] 29차 라이브 코테 제출

test29/문제2/임동민.js, test29/문제3/임동민.js
=> [임동민] 29차 라이브 코테 제출

test30/문제1/박희경.py, test30/문제2/박희경.py, test30/문제3/박희경.py
=> [박희경] 30차 라이브 코테 제출

test31/문제1/임동민.js, test31/문제2/임동민.js, test31/문제3/임동민.js
=> [임동민] 31차 라이브 코테 제출

test31/문제1/박희경.py, test31/문제2/박희경.py, test31/문제3/박희경.py
=> [박희경] 31차 라이브 코테 제출

test32/문제1/김진용.py, test32/문제2/김진용.py, test32/문제3/김진용.py
=> [김진용] 32차 라이브 코테 제출

test32/문제1/황장현.js, test32/문제2/황장현.js, test32/문제3/황장현.js
=> [황장현] 32차 라이브 코테 제출

test32/문제1/박희경.py, test32/문제2/박희경.py, test32/문제3/박희경.py
1: O
2: O (결국 참고..)
3: X (시도 x) → 다시 풀 때 참고
=> [박희경] 32차 라이브 코테 제출

test28/문제2/임동민.js, test31/문제2/임동민.js, test32/문제1/임동민.js, test32/문제2/임동민.js, test32/문제3/임동민.js
=> [임동민] 32차 라이브 코테 제출

test33/문제1/임동민.js, test33/문제2/임동민.js, test33/문제3/임동민.js
=> [임동민] 33차 라이브 코테 제출

test33/문제1/박희경.py, test33/문제2/박희경.py, test33/문제3/박희경.py
1: X (시도x)
2: X (시도x)
3: O (참고)
=> [박희경] 33차 라이브 코테 제출

test33/문제1/김진용.py, test33/문제2/김진용.py, test33/문제3/김진용.py
=> [김진용] 33차 라이브 코테 제출

test33/문제1/황장현.js, test33/문제2/황장현.js, test33/문제3/황장현.js
=> [황장현] 33차 라이브 코테 제출

test33/문제1/이지은.js, test33/문제2/이지은.js
=> [이지은] 33차 라이브 코테 제출

test34/문제1/임동민.js, test34/문제2/임동민.js, test34/문제3/임동민.js
=> [임동민] 34차 라이브 코테 제출

test34/문제2/김진용.py, test34/문제3/김진용.py
=> [김진용] 34차 라이브 코테 제출

test34/문제1/박희경.java, test34/문제2/빅희경.java, test34/문제3/박희경.java
=> [박희경] 34차 라이브 코테 제출

test34/문제1/황장현.js
=> [황장현] 34차 라이브 코테 제출

test34/문제1/정우희.js, test34/문제2/정우희.js, test34/문제3/정우희.js
=> [정우희] 34차 라이브 코테 제출

test35/문제1/임동민.js, test35/문제2/임동민.js, test35/문제3/임동민.js
=> [임동민] 35차 라이브 코테 제출

test35/문제1/황장현.js, test35/문제2/황장현.js, test35/문제3/황장현.js
=> [황장현] 35차 라이브 코테 제출

test35/문제1/박희경.py, test35/문제2/박희경.py
=> [박희경] 35차 라이브 코테 제출

test34/문제1/김진용.py, test35/문제1/김진용.py, test35/문제2/김진용.py, test35/문제3/김진용.py
=> [김진용] 35차 라이브 코테 제출

test36/문제1/최지혜.py, test36/문제2/최지혜.py, test36/문제3/최지혜.py
=> [최지혜] 36차 라이브코테 제출

test36/문제1/박희경.py, test36/문제2/박희경.py, test36/문제3/박희경.py
=> [박희경] 36차 라이브 코테 제출

test36/문제1/황장현.js, test36/문제2/황장현.js, test36/문제3/황장현.js
=> [황장현] 36차 라이브코테 제출

test37/문제1/임동민.js, test37/문제2/임동민.js, test37/문제3/임동민.js
=> [임동민] 37차 라이브 코테 제출

test37/문제1/김진용.py, test37/문제2/김진용.py, test37/문제3/김진용.py
=> [김진용] 37차 라이브 코테 제출

test37/문제1/최지혜.py
=> [최지혜] 37차 라이브 코테 제출

test37/문제1/박희경.py, test37/문제2/박희경.py, test37/문제3/박희경.py
=> [박희경] 37차 라이브 코테 제출

test38/문제1/김진용.py, test38/문제2/김진용.py, test38/문제3/김진용.py
1 - x(참고 x 거의 베낌)
2 - o
3 - x(참고)
=> [김진용] 38차 라이브 코테 제출

test38/문제1/박희경.py, test38/문제2/박희경.py, test38/문제3/박희경.py
=> [박희경] 38차 라이브 코테 제출

test38/문제2/최지혜.py, test38/문제3/최지혜.py
=> [최지혜] 38차 라이브코테 제출

test38/문제1/황장현.js
=> [황장현] 38차 라이브코테 제출

live3/test39/문제1/임동민.js, live3/test39/문제2/임동민.js, live3/test39/문제3/임동민.js
1-결석으로 인한 다시 푼 문제
2-결석으로 인한 다시 푼 문제
3-결석으로 인한 다시 푼 문제
=> [임동민] 39차 라이브 코테 제출

live3/test39/문제1/박희경.py, live3/test39/문제2/박희경.py, live3/test39/문제3/박희경.py
1: O (점화식 참고..)
2: O (점화식 참고..)
3: X
=> [박희경] 39차 라이브 코테 제출

live3/test40/문제1/황장현.js, live3/test40/문제2/황장현.js, live3/test40/문제3/황장현.js
1 - O(참고)
2 - 다시 푼 문제
3 - 다시 푼 문제
=> [황장현] 40차 라이브 코테 제출

live3/test40/문제1/임동민.js, live3/test40/문제2/임동민.js, live3/test40/문제3/임동민.js
=> [임동민] 40차 라이브 코테 제출

live4/test41/문제1/황장현.js, live4/test41/문제2/황장현.js, live4/test41/문제3/황장현.js
=> [황장현] 41차 라이브 코테 제출

live4/test41/문제1/박희경.py, live4/test41/문제2/박희경.py, live4/test41/문제3/박희경.py
=> [박희경] 41차 라이브 코테 제출

live4/test41/문제1/김진용.py, live4/test41/문제2/김진용.py, live4/test41/문제3/김진용.py
=> [김진용] 41차 라이브 코테 제출

live4/test41/문제1/임동민.js, live4/test41/문제2/임동민.js
=> [임동민] 41차 라이브 코테 제출

live4/test42/문제1/김진용.py, live4/test42/문제2/김진용.py, live4/test42/문제3/김진용.py
=> [김진용] 42차 라이브 코테 제출

live4/test42/문제1/최지혜.py, live4/test42/문제2/최지혜.py, live4/test42/문제3/최지혜.py
=> [최지혜] 42차 라이브코테 제출

live4/test42/문제1/황장현.js
=> [황장현] 42차 라이브코테 제출

live4/test43/문제1/황장현.js, live4/test43/문제3/황장현.js
=> [황장현] 43차 라이브코테 제출

live4/test42/문제2/박희경.py, live4/test43/문제1/박희경.py, live4/test43/문제2/박희경.py, live4/test43/문제3/박희경.py
=> [박희경] 43차 라이브 코테 제출

live4/test44/문제1/황장현.js, live4/test44/문제2/황장현.js, live4/test44/문제3/황장현.js
=> [황장현] 44차 라이브 코테 제출

live4/test44/문제1/박희경.py, live4/test44/문제2/박희경.py, live4/test44/문제3/박희경.py
=> [박희경] 44차 라이브 코테 제출

live4/test44/문제1/임동민.js, live4/test44/문제2/임동민.js, live4/test44/문제3/임동민.js
=> [임동민] 44차 라이브 코테 제출

live4/test45/문제1/황장현.js, live4/test45/문제2/황장현.js, live4/test45/문제3/황장현.js
=> [황장현] 45차 라이브 코테 제출

live4/test45/문제1/임동민.js, live4/test45/문제2/임동민.js, live4/test45/문제3/임동민.js
=> [임동민] 45차 라이브코테 제출

live4/test46/문제1/김진용.py, live4/test46/문제2/김진용.py, live4/test46/문제3/김진용.py
=> [김진용] 46차 라이브 코테 제출

live4/test46/문제1/황장현.js, live4/test46/문제2/황장현.js, live4/test46/문제3/황장현.js
=> [황장현] 46차 라이브코테 제출

live4/test47/문제1/임동민.js, live4/test47/문제2/임동민.js, live4/test47/문제3/임동민.js
=> [임동민] 47차 라이브코테 제출

live4/test47/문제1/박희경.py, live4/test47/문제3/박희경.py
백준 사이트가 접속이 안 되는 이슈로 3번만 풀었습니다 ㅜ
=> [박희경] 47차 라이브 코테 제출

live4/test48/문제1/박희경.py, live4/test48/문제2/박희경.py, live4/test48/문제3/박희경.py
=> [박희경] 48차 라이브 코테 제출

live4/test48/문제1/김진용.py, live4/test48/문제2/김진용.py, live4/test48/문제3/김진용.py
1 - o
2 - o (유클리드 호제법 참고)
2 - x ..
=> [김진용] 48차 라이브 코테 제출

live4/test48/문제1/최지혜.py, live4/test48/문제2/최지혜.py
=> [최지혜] 48차 라이브코테 제출

live4/test49/문제1/김진용.py, live4/test49/문제2/김진용.py, live4/test49/문제3/김진용.py
=> [김진용] 49차 라이브 코테 제출

live4/test49/문제1/임동민.js, live4/test49/문제2/임동민.js, live4/test49/문제3/임동민.js
=> [임동민] 49차 라이브코테 제출

live4/test49/문제2/박희경.py, live4/test49/문제3/박희경.py
=> [박희경] 49차 라이브 코테 제출

live4/test50/문제1/김진용.py, live4/test50/문제2/김진용.py, live4/test50/문제3/김진용.py
=> [김진용] 50차 라이브 코테 제출

live4/test49/문제1/박희경.py, live4/test50/문제1/박희경.py, live4/test50/문제2/박희경.py
처음에 올릴 때 2번 커밋을 잘못 했네요..? 
1: X (다시 풀이)
2: O 
3: X
=> [박희경] 50차 라이브 코테 제출

live4/test50/문제1/황장현.js, live4/test50/문제2/황장현.js
=> [황장현] 50차 라이브 코테 제출

live5/test51/문제1/박희경.py, live5/test51/문제2/박희경.py, live5/test51/문제3/박희경.py
=> [박희경] 51차 라이브 코테 제출

live5/test51/문제1/황장현.js, live5/test51/문제2/황장현.js
=> [황장현] 51차 라이브 코테 제출

live5/test51/문제1/임동민.js, live5/test51/문제2/임동민.js, live5/test51/문제3/임동민.js
=> [임동민] 51차 라이브코테 제출

live5/test52/문제1/김진용.py, live5/test52/문제2/김진용.py, live5/test52/문제3/김진용.py
=> [김진용] 52차 라이브 코테 제출

live5/test52/문제1/박희경.py, live5/test52/문제2/박희경.py, live5/test52/문제3/박희경.py
=> [박희경] 52차 라이브 코테 제출

live5/test52/문제1/임동민.js, live5/test52/문제2/임동민.js, live5/test52/문제3/임동민.js
=> [임동민] 52차 라이브코테 제출

live5/test53/문제1/박희경.py, live5/test53/문제2/박희경.py, live5/test53/문제3/박희경.py
=> [박희경] 53차 라이브 코테 제출

live5/test54/문제1/황장현.js, live5/test54/문제2/황장현.js, live5/test54/문제3/황장현.js
=> [황장현] 54차 라이브 코테 제출

live5/test54/문제1/박희경.py, live5/test54/문제2/박희경.py, live5/test54/문제3/박희경.py
1: o
2: o
3: o (테스트케이스 12-14 실패로 gpt 도움받음)
=> [박희경] 54차 라이브 코테 제출

live5/test55/문제1/박희경.py, live5/test55/문제2/박희경.py, live5/test55/문제3/박희경.py
=> [박희경] 55차 라이브 코테 제출

live5/test55/문제1/김진용.py, live5/test55/문제2/김진용.py, live5/test55/문제3/김진용.py
=> [김진용] 55차 라이브 코테 제출

live5/test55/문제1/임동민.js, live5/test55/문제2/임동민.js, live5/test55/문제3/임동민.js
1-못 품 (시도 중)
2-못 품 (시도 중)
3-시도 X
=> [임동민] 55차 라이브코테 제출

live5/test56/문제1/임동민.js, live5/test56/문제2/임동민.js, live5/test56/문제3/임동민.js
=> [임동민] 56차 라이브코테 제출

live5/test56/문제1/황장현.js, live5/test56/문제2/황장현.js, live5/test56/문제3/황장현.js
=> [황장현] 56차 라이브 코테 제출

live5/test58/문제1/황장현.js, live5/test58/문제2/황장현.js, live5/test58/문제3/황장현.js
=> [황장현] 58차 라이브 코테 제출

live5/test59/문제1/임동민.js, live5/test59/문제2/임동민.js, live5/test59/문제3/임동민.js
=> [임동민] 59차 라이브코테 제출

live5/test59/문제1/황장현.js, live5/test59/문제2/황장현.js, live5/test59/문제3/황장현.js
=> [황장현] 59차 라이브 코테 제출

live5/test60/문제1/박희경.py, live5/test60/문제2/박희경.py, live5/test60/문제3/박희경.py
=> [박희경] 60차 라이브 코테 제출

live6/test61/문제1/최지혜.py, live6/test61/문제2/최지혜.py, live6/test61/문제3/최지혜.py
=> [최지혜] 61차 라이브코테 제출

live6/test61/문제1/황장현.js, live6/test61/문제2/황장현.js, live6/test61/문제3/황장현.js
=> [황장현] 61차 라이브 코테 제출

live6/test61/문제1/임동민.js, live6/test61/문제2/임동민.js, live6/test61/문제3/임동민.js
=> [임동민] 61차 라이브코테 제출

live6/test65/문제1/임동민.js, live6/test65/문제2/임동민.js, live6/test65/문제3/임동민.js
=> [임동민] 65차 라이브코테 제출

live6/test65/문제1/박희경.py, live6/test65/문제2/박희경.py, live6/test65/문제3/박희경.py
1: X (푸는 중)
2: O (참고)
3: X (시도x)
=> [박희경] 65차 라이브 코테 제출

live6/test65/문제1/황장현.js, live6/test65/문제2/황장현.js, live6/test65/문제3/황장현.js
=> [황장현] 65차 라이브 코테 제출

live6/test66/문제1/최지혜.py, live6/test66/문제2/최지혜.py, live6/test66/문제3/최지혜.py
=> [최지혜] 66차 라이브코테 제출

live6/test66/문제1/박희경.py, live6/test66/문제2/박희경.py, live6/test66/문제3/박희경.py
=> [박희경] 66차 라이브 코테 제출

live6/test66/문제1/황장현.js, live6/test66/문제2/황장현.js, live6/test66/문제3/황장현.js
=> [황장현] 66차 라이브 코테 제출

live6/test66/문제1/임동민.js, live6/test66/문제2/임동민.js, live6/test66/문제3/임동민.js
=> [임동민] 66차 라이브코테 제출

live6/test67/문제2/임동민.js, live6/test67/문제3/임동민.js
=> [임동민] 67차 라이브코테 제출

live6/test67/문제1/최지혜.py, live6/test67/문제2/최지혜.py, live6/test67/문제3/최지혜.py
=> [최지혜] 67차 라이브코테 제출

live6/test67/문제1/황장현.js, live6/test67/문제2/황장현.js
=> [황장현] 67차 라이브 코테 제출

live6/test67/문제1/박희경.py, live6/test67/문제2/박희경.py, live6/test67/문제3/박희경.py
=> [박희경] 67차 라이브 코테 제출

live6/test67/문제1/김진용.py
=> [김진용] 67차 라이브 코테 제출

live6/test68/문제1/최지혜.py, live6/test68/문제2/최지혜.py, live6/test68/문제3/최지혜.py
=> [최지혜] 68차 라이브코테 제출

live6/test68/문제1/황장현.js, live6/test68/문제2/황장현.js, live6/test68/문제3/황장현.js
=> [황장현] 68차 라이브 코테 제출

live6/test68/문제1/박희경.py, live6/test68/문제2/박희경.py, live6/test68/문제3/박희경.py
=> [박희경] 68차 라이브 코테 제출

live6/test69/문제2/최지혜.py, live6/test69/문제3/최지혜.py
=> [최지혜] 69차 라이브코테 제출

live6/test69/문제1/황장현.js
=> [황장현] 69차 라이브 코테 제출

live6/test70/문제1/임동민.js, live6/test70/문제2/임동민.js, live6/test70/문제3/임동민.js
=> [임동민] 70차 라이브코테 제출

live6/test70/문제1/황장현.js, live6/test70/문제2/황장현.js, live6/test70/문제3/황장현.js
=> [황장현] 70차 라이브 코테 제출

live7/test71/문제1/임동민.js, live7/test71/문제2/임동민.js, live7/test71/문제3/임동민.js
=> [임동민] 71차 라이브코테 제출

live7/test71/문제1/박희경.py, live7/test71/문제2/박희경.py, live7/test71/문제3/박희경.py
=> [박희경] 71차 라이브 코테 제출

live7/test71/문제1/최지혜.py, live7/test71/문제2/최지혜.py, live7/test71/문제3/최지혜.py
=> [최지혜] 71차 라이브코테 제출

live7/test72/문제1/박희경.py, live7/test72/문제2/박희경.py, live7/test72/문제3/박희경.py
=> [박희경] 72차 라이브 코테 제출

live7/test72/문제2/임동민.js, live7/test72/문제3/임동민.js
=> [임동민] 72차 라이브코테 제출

live7/test74/문제1/황장현.js, live7/test74/문제2/황장현.js
=> [황장현] 74차 라이브 코테 제출

live7/test75/문제1/박희경.py, live7/test75/문제2/박희경.py, live7/test75/문제3/박희경.py
=> [박희경] 75차 라이브 코테 제출

live7/test74/문제3/황장현.js, live7/test75/문제1/황장현.js, live7/test75/문제2/황장현.js, live7/test75/문제3/황장현.js
=> [황장헌] 75차 라이브 코테 제출

live7/test76/문제1/박희경.py, live7/test76/문제2/박희경.py, live7/test76/문제3/박희경.py
=> [박희경] 76차 라이브 코테 제출

live7/test76/문제1/황장현.js, live7/test76/문제2/황장현.js
=> [황장현] 76차 라이브 코테 제출

live7/test77/문제1/박희경.py, live7/test77/문제2/박희경.py, live7/test77/문제3/박희경.py
=> [박희경] 77차 라이브 코테 제출

live7/test77/문제2/최지혜.java
=> [최지혜] 77차 라이브코테 제출

live7/test77/문제1/황장현.js, live7/test77/문제2/황장현.js
=> [황장현] 77차 라이브 코테 제출

live7/test77/문제3/황장현.js, live7/test78/문제1/황장현.js, live7/test78/문제2/황장현.java, live7/test78/문제3/황장현.js
=> [황장현] 78차 라이브 코테 제출

live7/test79/문제1/황장현.js, live7/test79/문제2/황장현.js, live7/test79/문제3/황장현.js
=> [황장현] 79차 라이브 코테 제출

live7/test79/문제1/최지혜.java, live7/test79/문제2/최지혜.java
=> [최지혜] 79차 라이브코테 제출

live7/test79/문제1/박희경.py, live7/test79/문제2/박희경.py, live7/test79/문제3/박희경.py
=> [박희경] 79차 라이브 코테 제출

live7/test80/문제1/윤정은.py
=> [윤정은] 80차 라이브 코테 제출

live7/test80/문제1/황장현.js
=> [황장현] 80차 라이브 코테 제출

live7/test80/문제1/박희경.py, live7/test80/문제2/박희경.py, live7/test80/문제3/박희경.py
=> [박희경] 80차 라이브 코테 제출

live8/test81/문제1/박희경.py, live8/test81/문제2/박희경.py, live8/test81/문제3/박희경.py
=> [박희경] 81차 라이브 코테 제출

live8/test81/문제1/황장현.js, live8/test81/문제2/황장현.js, live8/test81/문제3/황장현.js
=> [황장현] 81차 라이브 코테 제출

live8/test82/문제1/황장현.js, live8/test82/문제2/황장현.js
=> [황장현] 82차 라이브 코테 제출

live8/test82/문제1/박희경.py, live8/test82/문제2/박희경.py
=> [박희경] 82차 라이브 코테 제출

live8/test83/문제1/박희경.py, live8/test83/문제2/박희경.py, live8/test83/문제3/박희경.py
=> [박희경] 83차 라이브 코테 제출

live8/test82/문제2/황장현.js, live8/test83/문제1/황장현.js, live8/test83/문제2/황장현.js
=> [황장현] 83차 라이브 코테 제출

live8/test84/문제1/박희경.py, live8/test84/문제2/박희경.py, live8/test84/문제3/박희경.py
=> [박희경] 84차 라이브 코테 제출

live8/test85/문제1/이상민.js, live8/test85/문제2/이상민.js, live8/test85/문제3/이상민.js
=> [이상민] 85차 라이브 코테 제출

live8/test85/문제1/황장현.js, live8/test85/문제2/황장현.js, live8/test85/문제3/황장현.js
=> [황장현] 85차 라이브 코테 제출

live8/test87/문제1/박희경.py, live8/test87/문제2/박희경.py, live8/test87/문제3/박희경.py
1: o (매우 참고..)
2: x (푸는중)
3: x
=> [박희경] 87차 라이브 코테 제출

live8/test87/문제1/황장현.js, live8/test87/문제3/황장현.js
=> [황장현] 87차 라이브 코테 제출

live8/test87/문제1/백한결.py, live8/test87/문제2/백한결.py, live8/test87/문제3/백한결.py
=> [백한결] 87차 라이브 코테 제출

live8/test87/문제1/백유진.py, live8/test87/문제2/백유진.py, live8/test87/문제3/백유진.py
=> [백유진] 87차 라이브 코테 제출

live8/test87/문제1/이상민.js, live8/test87/문제2/이상민.js, live8/test87/문제3/이상민.js
=> [이상민] 87차 라이브 코테 제출

live8/test88/문제1/이상민.js, live8/test88/문제2/이상민.js, live8/test88/문제3/이상민.js
=> [이상민] 88차 라이브 코테 제출

live8/test88/문제1/백한결.py, live8/test88/문제2/백한결.py, live8/test88/문제3/백한결.py
1. x (참고)
2. x (백준 input..)
3. o
=> [백한결] 88차 라이브 코테 제출

live8/test88/문제1/백유진.py, live8/test88/문제2/백유진.py, live8/test88/문제3/백유진.py
=> [백유진] 88차 라이브 코테 제출

live8/test88/문제1/황장현.js, live8/test88/문제2/황장현.js, live8/test88/문제3/황장현.js
=> [황장현] 88차 라이브 코테 제출

live8/test89/문제1/이상민.js, live8/test89/문제2/이상민.js, live8/test89/문제3/이상민.js
=> [이상민] 89차 라이브 코테 제출

live8/test89/문제1/황장현.js, live8/test89/문제2/황장현.js, live8/test89/문제3/황장현.js
=> [황장현] 89차 라이브 코테 제출

live8/test89/문제1/박희경.py, live8/test89/문제2/박희경.py, live8/test89/문제3/박희경.py
=> [박희경] 89차 라이브 코테 제출

live8/test89/문제1/백유진.py, live8/test89/문제2/백유진.py, live8/test89/문제3/백유진.py
=> [백유진] 89차 라이브 코테 제출

live8/test90/문제1/황장현.js, live8/test90/문제2/황장현.js, live8/test90/문제3/황장현.js
=> [황장현] 90차 라이브 코테 제출

live8/test90/문제1/백유진.py, live8/test90/문제2/백유진.py, live8/test90/문제3/백유진.py
=> [백유진] 90차 라이브 코테 제출

live8/test90/문제1/박희경.py, live8/test90/문제2/박희경.py, live8/test90/문제3/박희경.py
=> [박희경] 90차 라이브 코테 제출

live9/test91/문제1/황장현.js, live9/test91/문제2/황장현.js, live9/test91/문제3/황장현.js
=> [황장현] 91차 라이브 코테 제출

live9/test91/문제1/박희경.py, live9/test91/문제2/박희경.py, live9/test91/문제3/박희경.py
=> [박희경] 91차 라이브 코테 제출

live9/test91/문제1/백한결.py, live9/test91/문제2/백한결.py, live9/test91/문제3/백한결.py
=> [백한결] 91차 라이브 코테 제출

live9/test91/문제1/백유진.py, live9/test91/문제2/백유진.py, live9/test91/문제3/백유진.py
=> [백유진] 91차 라이브 코테 제출

live9/test92/문제1/황장현.js, live9/test92/문제2/황장현.js, live9/test92/문제3/황장현.js
=> [황장현] 92차 라이브 코테 제출

live9/test93/문제1/박희경.py, live9/test93/문제2/박희경.py, live9/test93/문제3/박희경.py
=> [박희경] 93차 라이브 코테 제출

live9/test93/문제1/백유진.py, live9/test93/문제2/백유진.py
=> [백유진] 93차 라이브 코테 제출

live9/test93/문제1/황장현.js, live9/test93/문제2/황장현.js
=> [황장현] 93차 라이브 코테 제출

live9/test93/문제1/백한결.py, live9/test93/문제2/백한결.py, live9/test93/문제3/백한결.py
=> [백한결] 93차 라이브 코테 제출

live9/test95/문제1/박희경.py, live9/test95/문제2/박희경.py, live9/test95/문제3/박희경.py
=> [박희경] 95차 라이브 코테 제출

live9/test95/문제1/백유진.py, live9/test95/문제2/백유진.py, live9/test95/문제3/백유진.py
=> [백유진] 95차 라이브 코테 제출

live9/test95/문제1/황장현.js, live9/test95/문제2/황장현.js
=> [황장현] 95차 라이브 코테 제출

live9/test96/문제1/조진우.js, live9/test96/문제2/조진우.js, live9/test96/문제3/조진우.js
1. X(BFS 기초 공부를 먼저 좀 해야 할 듯...)
2. O
3. O
=> [조진우] 96차 라이브 코테 제출

live9/test96/문제1/박희경.py, live9/test96/문제2/박희경.py, live9/test96/문제3/박희경.py
=> [박희경] 96차 라이브 코테 제출

live9/test96/문제1/백한결.py, live9/test96/문제2/백한결.py, live9/test96/문제3/백한결.py
=> [백한결] 96차 라이브 코테 제출

live9/test97/문제3/황장현.js
=> [황장현] 97차 라이브 코테 제출

live9/test97/문제1/백한결.py, live9/test97/문제2/백한결.py, live9/test97/문제3/백한결.py
=> [백한결] 97차 라이브 코테 제출

live9/test97/문제1/백유진.py, live9/test97/문제2/백유진.py, live9/test97/문제3/백유진.py
=> [백유진] 97차 라이브 코테 제출

live9/test97/문제1/조진우.js, live9/test97/문제2/조진우.js
1: O
2: O
3: x(조금 더 공부해 봐야 할 듯 합니다)
=> [조진우] 97차 라이브 코테 제출

live9/test97/문제1/박희경.py, live9/test97/문제2/박희경.py, live9/test97/문제3/박희경.py
=> [박희경] 97차 라이브 코테 제출

live9/test98/문제1/조진우.js, live9/test98/문제2/조진우.js, live9/test98/문제3/조진우.js
=> [조진우] 98차 라이브 코테 제출

live9/test98/문제1/백유진.py, live9/test98/문제2/백유진.py, live9/test98/문제3/백유진.py
=> [백유진] 98차 라이브 코테 제출

live9/test98/문제1/황장현.js, live9/test98/문제2/황장현.js, live9/test98/문제3/황장현.js
=> [황장현] 98차 라이브 코테 제출

live9/test98/문제1/박희경.py, live9/test98/문제2/박희경.py, live9/test98/문제3/박희경.py
=> [박희경] 98차 라이브 코테 제출

live9/test99/문제1/황장현.js, live9/test99/문제2/황장현.js, live9/test99/문제3/황장현.js
=> [황장현] 99차 라이브 코테 제출

live9/test99/문제1/백한결.py, live9/test99/문제2/백한결.py, live9/test99/문제3/백한결.py
=> [백한결] 99차 라이브 코테 제출

live9/test99/문제1/박희경.py, live9/test99/문제2/박희경.py, live9/test99/문제3/박희경.py
1: o (참고)
2: o (백트래킹으로 풀고 싶었으나 .. )
3: x (푸는중)
=> [박희경] 99차 라이브 코테 제출

.gitignore, live9/test99/문제1/조진우.js, live9/test99/문제2/조진우.js, live9/test99/문제3/조진우.js
=> [조진우] 99차 라이브 코테 제출

live9/test99/문제1/백유진.py, live9/test99/문제2/백유진.py, live9/test99/문제3/백유진.py
=> [백유진] 99차 라이브 코테 제출

live9/test100/문제1/박희경.py, live9/test100/문제2/박희경.py, live9/test100/문제3/박희경.py
=> [박희경] 100차 라이브 코테 제출

live9/test100/문제1/황장현.js, live9/test100/문제2/황장현.js
=> [황장현] 100차 라이브 코테 제출

live9/test100/문제1/백한결.py, live9/test100/문제2/백한결.py, live9/test100/문제3/백한결.py
=> [백한결] 100차 라이브 코테 제출

live9/test100/문제1/백유진.py, live9/test100/문제3/백유진.py
=> [백유진] 100차 라이브 코테 제출

live9/test100/문제1/조진우.js, live9/test100/문제2/조진우.js, live9/test100/문제3/조진우.js
=> [조진우] 100차 라이브 코테 제출

live10/test101/문제1/박희경.py, live10/test101/문제2/박희경.py, live10/test101/문제3/박희경.py
=> [박희경] 101차 라이브 코테 제출

live10/test101/문제1/황장현.js, live10/test101/문제2/황장현.js, live10/test101/문제3/황장현.js, live9/test100/문제2/황장현.js, live9/test100/문제3/황장현.js
100차 다시 푼 문제  2, 3번 커밋 추가
--- 
1-0
2-0
3-x
=> [황장현] 101차 라이브 코테 제출

live10/test101/문제1/조진우.js, live10/test101/문제2/조진우.js, live10/test101/문제3/조진우.js
=>  [조진우] 101차 라이브 코테 제출

live10/test101/문제1/백한결.py, live10/test101/문제2/백한결.py, live10/test101/문제3/백한결.py
=> [백한결] 101차 라이브 코테 제출

live10/test102/문제1/황장현.js, live10/test102/문제2/황장현.js
=> [황장현] 102차 라이브 코테 제출

live10/test102/문제1/박희경.py, live10/test102/문제2/박희경.py, live10/test102/문제3/박희경.py
=> [박희경] 102차 라이브 코테 제출

live10/test102/문제1/조진우.js, live10/test102/문제2/조진우.js, live10/test102/문제3/조진우.js
=> [조진우] 102차 라이브 코테 제출

live10/test103/문제1/황장현.js, live10/test103/문제3/황장현.js
=> [황장현] 103차 라이브 코테 제출

live10/test103/문제1/박희경.py, live10/test103/문제2/박희경.py, live10/test103/문제3/박희경.py
=> [박희경] 103차 라이브 코테 제출

live10/test103/문제1/조진우.js, live10/test103/문제2/조진우.js, live10/test103/문제3/조진우.js
=> [조진우] 103차 라이브 코테 제출

live10/test104/문제1/조진우.js, live10/test104/문제2/조진우.js, live10/test104/문제3/조진우.js
23:30 ~ 00:30 라이브 코테 진행
1. O
2. X(거의 다 풂)
3. X
=> [조진우] 104차 라이브 코테 제출

live10/test104/문제1/황장현.js, live10/test104/문제2/황장현.js, live10/test104/문제3/황장현.js
=> [황장현] 104차 라이브 코테 제출

live10/test104/문제1/백한결.py, live10/test104/문제2/백한결.py, live10/test104/문제3/백한결.py
=> [백한결] 104차 라이브 코테 제출

live10/test104/문제1/박희경.py, live10/test104/문제2/박희경.py, live10/test104/문제3/박희경.py
=> [박희경] 104차 라이브 코테 제출

live10/test105/문제2/백한결.py, live10/test105/문제3/백한결.py
=> [백한결] 105차 라이브 코테 제출

live10/test105/문제1/박희경.py, live10/test105/문제2/박희경.py, live10/test105/문제3/박희경.py
=> [박희경] 105차 라이브 코테 제출

live10/test105/문제1/황장현.js, live10/test105/문제3/황장현.js
=> [황장현] 105차 라이브 코테 제출

live10/test105/문제1/조진우.js, live10/test105/문제2/조진우.js, live10/test105/문제3/조진우.js
=> [조진우] 105차 라이브 코테 제출

live10/test106/문제1/박희경.py, live10/test106/문제2/박희경.py, live10/test106/문제3/박희경.py
=> [박희경] 106차 라이브 코테 제출

live10/test105/문제1/백한결.py, live10/test106/문제1/백한결.py, live10/test106/문제2/백한결.py, live10/test106/문제3/백한결.py
1. o
2. x (푸는 중)
3. o
+ 깜빡하고 105차 1번문제를 풀고 안올렸어서 이 PR에 같이 올립니다..!
=> [백한결] 106차 라이브 코테 제출

live10/test106/문제1/조진우.js, live10/test106/문제2/조진우.js, live10/test106/문제3/조진우.js
=> [조진우] 106차 라이브 코테 제출

live10/test107/문제1/박희경.py, live10/test107/문제2/박희경.py, live10/test107/문제3/박희경.py
=> [박희경] 107차 라이브 코테 제출

live10/test107/문제1/조진우.js, live10/test107/문제2/조진우.js, live10/test107/문제3/조진우.js
=> [조진우] 107차 라이브 코테 제출

live10/test107/문제1/백한결.py, live10/test107/문제2/백한결.py, live10/test107/문제3/백한결.py
=> [백한결] 107차 라이브 코테 제출

.github/workflows/merge-and-generate-problems.yml, live10/test107/문제1/황장현.js, live10/test107/문제2/황장현.js, live10/test107/문제3/황장현.js
=> [황장현] 107차 라이브 코테 제출

live10/test108/문제1/박희경.py, live10/test108/문제2/박희경.py, live10/test108/문제3/박희경.py
1: o (참고)
2: x ( 푸는중)
3: x
미쳤다
=> [박희경] 108차 라이브 코테 제출

live10/test108/문제1/황장현.js, live10/test108/문제2/황장현.js
=> [황장현] 108차 라이브 코테 제출

live10/test108/문제1/백한결.py, live10/test108/문제2/백한결.py, live10/test108/문제3/백한결.py
=> [백한결] 108차 라이브 코테 제출

live10/test109/문제1/박희경.py, live10/test109/문제2/박희경.py
=> [박희경] 109차 라이브 코테 제출

live10/test110/문제1/백한결.py, live10/test110/문제2/백한결.py
=> [백한결] 110차 라이브 코테 제출

live10/test110/문제1/조진우.js, live10/test110/문제2/조진우.js
=> [조진우] 110차 라이브 코테 제출

live10/test110/문제1/박희경.py, live10/test110/문제2/박희경.py
=> [박희경] 110차 라이브 코테 제출

live11/test111/문제1/백한결.py, live11/test111/문제2/백한결.py
=> [백한결] 111차 라이브 코테 제출

live11/test111/문제1/박희경.py, live11/test111/문제2/박희경.py
=> [박희경] 111차 라이브 코테 제출

live11/test112/문제1/조진우.js, live11/test112/문제2/조진우.js
=> [조진우] 112차 라이브 코테 제출

live11/test112/문제1/황장현.js, live11/test112/문제2/황장현.js
=> [황장현] 112차 라이브 코테 제출

live11/test112/문제1/백한결.py, live11/test112/문제2/백한결.py
=> [백한결] 112차 라이브 코테 제출

live11/test112/문제1/박희경.py, live11/test112/문제2/박희경.py
=> [박희경] 112차 라이브 코테 제출

live11/test113/문제1/박희경.py, live11/test113/문제2/박희경.py
=> [박희경] 113차 라이브 코테 제출

live11/test113/문제1/황장현.js
=> [황장현] 113차 라이브 코테 제출

live11/test113/문제1/조진우.js, live11/test113/문제2/조진우.js
=> [조진우] 113차 라이브 코테 제출

live11/test113/문제1/백한결.py, live11/test113/문제2/백한결.py
=> [백한결] 113차 라이브 코테 제출

live11/test114/문제1/백한결.py, live11/test114/문제2/백한결.py
=> [백한결] 114차 라이브 코테 제출

live11/test114/문제1/박희경.py, live11/test114/문제2/박희경.py
=> [박희경] 114차 라이브 코테 제출

live11/test114/문제1/조진우.js, live11/test114/문제2/조진우.js
=> [조진우] 114차 라이브 코테 제출

live11/test115/문제1/백한결.py, live11/test115/문제2/백한결.py
=> [백한결] 115차 라이브 코테 제출

live11/test115/문제1/박희경.py, live11/test115/문제2/박희경.py
=> [박희경] 115차 라이브 코테 제출

live11/test116/문제1/백한결.py, live11/test116/문제2/백한결.py
=> [백한결] 116차 라이브 코테 제출

live11/test116/문제1/박희경.py, live11/test116/문제2/박희경.py
=> [박희경] 116차 라이브 코테 제출

live11/test117/문제1/박희경.py, live11/test117/문제2/박희경.py
=> [박희경] 117차 라이브 코테 제출

live11/test118/문제1/황장현.js, live11/test118/문제2/황장현.js
=> [황장현] 118차 라이브 코테 제출

live11/test118/문제1/박희경.py, live11/test118/문제2/박희경.py
=> [박희경] 118차 라이브 코테 제출

live11/test119/문제1/백한결.py, live11/test119/문제2/백한결.py
=> [백한결] 119차 라이브 코테 제출

live11/test119/문제2/박희경.py, live11/test120/문제1/박희경.py
1: x (시간초과..)
2: x
119차 2번 문제 다시 푼 문제도 같이 PR 올립니다
=> [박희경] 120차 라이브 코테 제출

live12/test121/문제1/백한결.py, live12/test121/문제2/백한결.py
=> [백한결] 121차 라이브 코테 제출

live12/test121/문제1/박희경.py
=> [박희경] 121차 라이브 코테 제출

live12/test121/문제1/황장현.js
=> [황장현] 121차 라이브 코테 제출
